version: '3.8'
services:
  postgres_db:
    container_name: my_postgres
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app-network
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: happy_care_auth_server
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres_db
      - redis
  redis:
    container_name: hc_redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
