version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: happy_care_auth_server
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: yarn start:prod
    restart: always
    depends_on:
      - postgres_db
      - redis
  postgres_db:
    container_name: hc_postgres
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - app-network
  redis:
    container_name: hc_redis
    image: redis:6.2-alpine
    ports:
      - "6579:6379"
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
