/* eslint-disable @typescript-eslint/naming-convention */
import { ENUM_PERMISSION_MODULE } from 'src/modules/permission/constants';

export const PERMISSIONS = Object.freeze({
	BASIC: {
		code: 0,
		name: 'basic',
		description: 'Basic permission',
		module: ENUM_PERMISSION_MODULE.BASIC,
	},
	READ_USER_PROFILE: {
		code: 10,
		name: 'read_user_profile',
		description: 'can_read_user_profile',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	UPDATE_USER_PROFILE: {
		code: 20,
		name: 'update_user_profile',
		description: 'can_update_user_profile',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	CREATE_CATEGORY: {
		code: 30,
		name: 'create_category',
		description: 'can_create_category',
		module: ENUM_PERMISSION_MODULE.CATEGORY,
	},
	CREATE_PRODUCT: {
		code: 40,
		name: 'create_product',
		description: 'can_create_product',
		module: ENUM_PERMISSION_MODULE.PRODUCT,
	},
	CREATE_PERMISSION: {
		code: 50,
		name: 'create_permission',
		description: 'can_create_permission',
		module: ENUM_PERMISSION_MODULE.PERMISSION,
	},
	READ_PERMISSION: {
		code: 60,
		name: 'read_permission',
		description: 'can_read_permission',
		module: ENUM_PERMISSION_MODULE.PERMISSION,
	},
	UPDATE_PERMISSION: {
		code: 70,
		name: 'update_permission',
		description: 'can_update_permission',
		module: ENUM_PERMISSION_MODULE.PERMISSION,
	},
	READ_ROLE: {
		code: 80,
		name: 'read_role',
		description: 'can_read_role',
		module: ENUM_PERMISSION_MODULE.ROLE,
	},
	UPDATE_ROLE: {
		code: 90,
		name: 'update_role',
		description: 'can_update_role',
		module: ENUM_PERMISSION_MODULE.ROLE,
	},
	UPDATE_CATEGORY: {
		code: 100,
		name: 'update_category',
		description: 'can_update_category',
		module: ENUM_PERMISSION_MODULE.CATEGORY,
	},
	UPDATE_PRODUCT: {
		code: 110,
		name: 'update_product',
		description: 'can_update_product',
		module: ENUM_PERMISSION_MODULE.PRODUCT,
	},
	READ_ALL_USER_CART: {
		code: 120,
		name: 'read_all_user_cart',
		description: 'can_read_all_user_cart',
		module: ENUM_PERMISSION_MODULE.CART,
	},
	READ_USER_CART: {
		code: 130,
		name: 'read_user_cart',
		description: 'can_read_user_cart',
		module: ENUM_PERMISSION_MODULE.CART,
	},
	CREATE_USER_CART: {
		code: 140,
		name: 'create_user_cart',
		description: 'can_create_user_cart',
		module: ENUM_PERMISSION_MODULE.CART,
	},
	UPDATE_USER_CART: {
		code: 150,
		name: 'update_user_cart',
		description: 'can_update_user_cart',
		module: ENUM_PERMISSION_MODULE.CART,
	},
	DELETE_USER_CART: {
		code: 160,
		name: 'delete_user_cart',
		description: 'can_delete_user_cart',
		module: ENUM_PERMISSION_MODULE.CART,
	},
	CREATE_USER_CART_ITEM: {
		code: 170,
		name: 'create_user_cart_item',
		description: 'can_create_user_cart_item',
		module: ENUM_PERMISSION_MODULE.CART,
	},
	UPDATE_USER_CART_ITEM: {
		code: 180,
		name: 'update_user_cart_item',
		description: 'can_update_user_cart_item',
		module: ENUM_PERMISSION_MODULE.CART,
	},
	DELETE_USER_CART_ITEM: {
		code: 190,
		name: 'delete_user_cart_item',
		description: 'can_delete_user_cart_item',
		module: ENUM_PERMISSION_MODULE.CART,
	},
	CREATE_BRANCH: {
		code: 200,
		name: 'create_branch',
		description: 'can_create_branch',
		module: ENUM_PERMISSION_MODULE.BRANCH,
	},
	UPDATE_BRANCH: {
		code: 210,
		name: 'update_branch',
		description: 'can_update_branch',
		module: ENUM_PERMISSION_MODULE.BRANCH,
	},
	DELETE_BRANCH: {
		code: 220,
		name: 'delete_branch',
		description: 'can_delete_branch',
		module: ENUM_PERMISSION_MODULE.BRANCH,
	},
	CREATE_ORIGIN: {
		code: 230,
		name: 'create_origin',
		description: 'can_create_origin',
		module: ENUM_PERMISSION_MODULE.ORIGIN,
	},
	UPDATE_ORIGIN: {
		code: 240,
		name: 'update_origin',
		description: 'can_update_origin',
		module: ENUM_PERMISSION_MODULE.ORIGIN,
	},
	DELETE_ORIGIN: {
		code: 250,
		name: 'delete_origin',
		description: 'can_delete_origin',
		module: ENUM_PERMISSION_MODULE.ORIGIN,
	},
	CREATE_FEEDBACK: {
		code: 260,
		name: 'create_feedback',
		description: 'can_create_feedback',
		module: ENUM_PERMISSION_MODULE.FEEDBACK,
	},
	UPDATE_FEEDBACK: {
		code: 270,
		name: 'update_feedback',
		description: 'can_update_feedback',
		module: ENUM_PERMISSION_MODULE.FEEDBACK,
	},
	DELETE_FEEDBACK: {
		code: 280,
		name: 'delete_feedback',
		description: 'can_delete_feedback',
		module: ENUM_PERMISSION_MODULE.FEEDBACK,
	},
	READ_ALL_USER: {
		code: 290,
		name: 'read_all_user',
		description: 'can_read_all_user',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	READ_USER: {
		code: 300,
		name: 'read_user',
		description: 'can_read_user',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	DELETE_TRADEMARK: {
		code: 310,
		name: 'delete_trademark',
		description: 'can_delete_trademark',
		module: ENUM_PERMISSION_MODULE.ORIGIN,
	},
	CREATE_PRODUCT_LOG: {
		code: 320,
		name: 'create_product_log',
		description: 'can_create_product_log',
		module: ENUM_PERMISSION_MODULE.PRODUCT_LOG,
	},
	UPDATE_USER_ROLE: {
		code: 330,
		name: 'update_user_role',
		description: 'can_update_user_role',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	CREATE_USER: {
		code: 340,
		name: 'create_user',
		description: 'can_create_user',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	READ_PRODUCT_LOG: {
		code: 350,
		name: 'read_product_log',
		description: 'can_read_product_log',
		module: ENUM_PERMISSION_MODULE.PRODUCT_LOG,
	},
	CREATE_MY_ORDER: {
		code: 360,
		name: 'create_my_order',
		description: 'can_create_my_order',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
	READ_MY_USER_SETTING: {
		code: 370,
		name: 'read_my_user_setting',
		description: 'can_read_my_user_setting',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	CREATE_MY_USER_SETTING: {
		code: 380,
		name: 'create_my_user_setting',
		description: 'can_create_my_user_setting',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	UPDATE_USER: {
		code: 390,
		name: 'update_user',
		description: 'can_update_user',
		module: ENUM_PERMISSION_MODULE.USER,
	},
	CREATE_ORDER: {
		code: 400,
		name: 'create_order',
		description: 'can_create_order',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
	READ_ORDER_HISTORY: {
		code: 410,
		name: 'read_order_history',
		description: 'can_read_order_history',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
	READ_ALL_ORDERS: {
		code: 420,
		name: 'read_all_orders',
		description: 'can_read_all_orders',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
	READ_TOTAL_ORDERS: {
		code: 430,
		name: 'read_total_orders',
		description: 'can_read_total_orders',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
	READ_ORDER: {
		code: 440,
		name: 'read_order',
		description: 'can_read_order',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
	UPDATE_ORDER_STATUS: {
		code: 450,
		name: 'update_order_status',
		description: 'can_update_order_status',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
	READ_REVENUE_YEAR: {
		code: 510,
		name: 'read_revenue_year',
		description: 'can_read_revenue_year',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
	READ_REVENUE_DAY: {
		code: 520,
		name: 'read_revenue_day',
		description: 'can_read_revenue_day',
		module: ENUM_PERMISSION_MODULE.ORDER,
	},
});
