/* eslint-disable @typescript-eslint/naming-convention */
export enum ENUM_AUTH_TOKEN_TYPES {
	ACCESS_TOKEN = 'ACCESS_TOKEN',
	REFRESH_TOKEN = 'REFRESH_TOKEN',
}

export enum ENUM_AUTH_ACCESS_LEVEL_SUPER_ADMIN {
	SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum ENUM_AUTH_ACCESS_LEVEL_DEFAULT {
	ADMIN = 'ADMIN',
	PHARMACIST = 'PHARMACIST',
	CUSTOMER = 'CUSTOMER',
}

export const ENUM_AUTH_ACCESS_LEVEL = {
	...ENUM_AUTH_ACCESS_LEVEL_SUPER_ADMIN,
	...ENUM_AUTH_ACCESS_LEVEL_DEFAULT,
};

export type TYPE_AUTH_ACCESS_FOR =
	| ENUM_AUTH_ACCESS_LEVEL_SUPER_ADMIN
	| ENUM_AUTH_ACCESS_LEVEL_DEFAULT;
